services:
  - type: web
    name: whisper-transcriber
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: your_api_key_here
